### PR TITLE
[WIP] Update cwl rewrite tool

### PR DESCRIPTION
**Pull request by mvdbeek**
This works, but somewhere along the way we lose output labels

### CODE REVIEW

**Comment by jmchilton** [comment]
So this was in the branch - I didn't even notice 😆. Thanks for working on this! I assume missing output labels is pretty serious - like the workflow output labels right, or the tool form labels?

**Comment by mvdbeek** [comment]
Should be workflow output labels, I'll dump the converted documents when I'm done running the green tests.

**Comment by mr-c** [comment]
> Should be workflow output labels, I'll dump the converted documents when I'm done running the green tests.

Thanks @mvdbeek ; probably a bug in the refactoring tool; hopefully I'll be able to track it down quickly.

**Comment by mvdbeek** [comment]
Ah, I think the invocation simply failed ... I'll keep looking, but I don't think this is caused by the refactoring tool

**Comment by mvdbeek** [comment]
merged this as part of #132, will still need to rework this for a new cwlutils function that processes 1.0/1.1/1.2 documents as necessary.

**Comment by mr-c** [comment]
> merged this as part of #132, will still need to rework this for a new cwlutils function that processes 1.0/1.1/1.2 documents as necessary.

This is done!
https://github.com/common-workflow-language/cwl-utils/blob/main/cwl_utils/cwl_expression_refactor.py

**Pull request closed without merging**
